home page created
irenekurien/puzzles-2.0 pull request #2
Opened 2021-11-13 17:07 UTC by anandukch

2021-11-15 10:37 UTC, UKnowWhoIm commented
- Make meaningful commit messages
- Regarding video quality, the original video resolution is low(960x402), maybe due to compression by whatsapp?
- There was a page before the video right?
- Mute button :smile: 

@anandukch

2021-11-15 10:54 UTC, anandukch commented
- Yes Sure😅😅
- Yes, it mIght be the reason
- Which page??
- 😎😎😎😎

2021-11-15 13:09 UTC, irenekurien commented
>     * There was a page before the video right?
> 
> @UKnowWhoIm @anandukch Not a page, it's like an overlay for some sec till the video loads.

2021-11-18 14:26 UTC, UKnowWhoIm commented
That "mute button" animation makes sense for loading screen's, not for mute/unmute, I think we could find use for that during loading.

For this case, try https://fontawesome.com/v6.0/icons?q=volume&s=solid%2Cbrands buttons, we'll some lose immersion, but I think this is the best way forward

2021-11-20 15:57 UTC, irenekurien commented
@anandukch Replace the video with the original (non compressed) one

2021-11-20 16:00 UTC, anandukch commented
original video got lost from adarsh ser @irenekurien

2021-11-20 16:08 UTC, irenekurien requested changes

2021-11-20 16:08 UTC, irenekurien commented on js/script.js
> +var splash = document.querySelector(".splash-screen");
Don't use var, replace it with let or const accordingly

2021-11-20 16:53 UTC, irenekurien commented
> original video got lost from adarsh ser @irenekurien

Great 🌔

2021-11-20 17:35 UTC, irenekurien approved these changes

2021-11-20 17:35 UTC, merged